export const GET_LAT_LON_REQUEST = "GET_LAT_LON_REQUEST";
export const GET_LAT_LON_ERROR = "GET_LAT_LON_ERROR";

export const GET_WEATHER_REQUEST = "GET_WEATHER_REQUEST";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_ERROR = "GET_WEATHER_ERROR";
